@startuml Diagrama

class JuegoZoroAventuras{
    + Jugar()
    + Velocidad()
    - Texture texture
    - Event eventClose
    - Clock scoreClock
    - Clock obstaClock
    - Music characterMusic
}

class Vida{
    + Vida()
    + Uptdate(VidaActual)
    + Draw()
    - Font fontLiveLevel
    - Text liveText
}

class Puntaje{
    + Puntaje()
    + Uptdate(Score)
    + Draw()
    - Font scoreFont
    - Text scoreText
    - Clock scoreClock
}

class Personaje{
    + Personaje(Position)
    + Uptdate()
    + Draw()
    + Musica()
    + Move(Position)
    + Quieto()
    - Texture zoroTexture
    - Sprite zoroSprite
    - Clock Characterclock
}

class Pantalla{
    + Pantalla()
    + Draw()
    + Musica()
    + Musica2()
    - Text titleText
    - Text startText
    - Font titleFont
    - Font startFont
    - Music startMusic
    - Sprite backgroundSprite
    - Texture backgroundTexture
}

class Obstaculo{
    + Sprite spriteTornado
    + Obstaculo(Position)
    + Uptdate()
    + Draw()
    + Move(Position)
    - Texture obstacTexture
    - Clock obstaclock
    - float frameTime
    - int currentFrame 
    - int numFrames
    - int frameWidth
    - int frameHeight
}

class GameOver{
    + int FinalScore(FinalScore)
    + Background()
    + Draw()
    - Font gameOverFont
    - Text gameOverText
    - Text scoreText
    - Texture backgroundTexture
    - Sprite backgroundSprite
    - int Score
}

class FinalScore
class Zoro
class Contador
class Position
class Score
class JuegoPrincipal
class VidaActual

JuegoZoroAventuras "1" -|> "1" JuegoPrincipal
JuegoZoroAventuras "1" *-- "1" Puntaje
JuegoZoroAventuras "1" o-- "1" Pantalla
JuegoZoroAventuras "1" *-- "1" Personaje
JuegoZoroAventuras "1" *-- "*" Obstaculo

Pantalla "1" o-- "1" GameOverScreen

Vida "1" -|> "1" Contador
Vida "1" o-- "1" VidaActual

Puntaje "1" -|> "1" Contador
Puntaje "1" o-- "1" Score

Pantalla "1" *-- "2" Contador

Zoro "1" o-- "*" Position
Obstaculo "1" o-- "*" Position

Zoro "1"*--"1" Vida
Zoro "1" o-- "*" Obstaculo
Zoro "1" -|> "1" Personaje

GameOverScreen "1" o-- "1" FinalScore

@enduml